Actualizar precios
fpalorma/vet-anestesia pull request #11
Opened 2024-02-18 14:41 UTC by fpalorma

Se cambio el valor del tamaño de la droga Medeto

2024-02-18 16:08 UTC, agusst requested changes

2024-02-18 16:08 UTC, agusst commented on src/app/components/main-form/index.jsx
> +        defaultValue= ''
Se te escapó un espacio, no debería quedar separado

2024-02-18 17:33 UTC, agusst commented on src/app/components/main-form/index.jsx
> +        defaultValue= ''
No veo el cambio, hiciste el commit?

2024-02-18 20:01 UTC, fpalorma commented on src/app/components/main-form/index.jsx
> +        defaultValue= ''
Quizas ahora, no habia pusheado el cambio

2024-02-19 00:34 UTC, agusst approved these changes

2024-02-19 00:35 UTC, merged